# version: '3.1'
# services:
#   mongo:
#     container_name: ${MONGODB_HOST}
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
#     ports:
#       - ${MONGODB_PORT}:${MONGODB_PORT}
#     volumes:
#       - ./mongo-data:/data/db
#     restart: unless-stopped

version: '3.1'

services:
  mongo:
    container_name: my_mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped
